ESTABLISHMENT = 'establishment'
LOCATION = 'location'
CONTACT = 'contact'
POST = 'POST'
INVALID_CREDENTIALS = 'INVALID_LOGIN_CREDENTIALS'
SUCCESS = 'Success'
ERROR = 'Error'
EMAIL = 'email'
AMENITIES = 'Amenities'
RESTAURANT = 'Restaurant'
EMAIL_EXISTS = 'EMAIL_EXISTS'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
PRODUCTS = 'products'
bucket_link = 'tourism-b7e72.appspot.com'
PENDING = 'Pending'
ACCEPT = 'Accept'
ACCEPTED = 'Accepted'
DENY = 'Deny'
DENIED = 'Denied'
PENDING = 'Pending'
PARTNERS = 'partners'
SERVICES = 'services'


HOTEL_RESTAURANT = 'Hotel & Restaurants'
ACCOMMODATION = 'Accommodations'
CAR_RENTAL = 'Vehicle Rentals'

SUCCESS = 'SUCCESS'
